import { useApi } from "@/hooks/useApi";
import { predictPatientRisk } from "@/services/api";
import type { Patient, RiskAssessment } from "@/types";
import Modal from "@/components/common/Modal";
import {
  fmtDate,
  fmtScore,
  riskBadgeClass,
} from "@/utils/format";

interface PatientDetailModalProps {
  patient: Patient | null;
  assessment: RiskAssessment | null;
  onClose: () => void;
}

function VitalTile({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-lg border border-line px-3 py-2.5">
      <p className="tabular-nums text-lg font-semibold leading-none">{value}</p>
      <p className="muted mt-1 text-[11px] uppercase tracking-wide">{label}</p>
    </div>
  );
}

export default function PatientDetailModal({
  patient,
  assessment,
  onClose,
}: PatientDetailModalProps) {
  const patientId = patient?.patient_id ?? null;
  const ml = useApi(
    () => (patientId ? predictPatientRisk(patientId) : Promise.resolve(null)),
    [patientId],
  );
  const prediction = ml.data;

  return (
    <Modal
      open={patient != null}
      onClose={onClose}
      title={patient ? `Patient ${patient.patient_id}` : ""}
      subtitle={
        patient ? `${patient.age} years · ${patient.gender} · ${patient.district}` : undefined
      }
    >
      {patient && (
        <div className="space-y-6">
          <div className="rounded-xl border border-line p-4">
            <div className="mb-3 flex flex-wrap items-center justify-between gap-2">
              <p className="panel-title">AI risk assessment</p>
              <div className="flex items-center gap-2">
                {ml.loading && (
                  <span className="muted animate-pulse text-[11px]">Running inference...</span>
                )}
                <button
                  type="button"
                  onClick={() => ml.refetch()}
                  disabled={ml.loading}
                  className="btn-primary h-7 px-2.5 text-[11px]"
                >
                  Run AI Assessment
                </button>
                {prediction ? (
                  <span
                    className={riskBadgeClass(
                      prediction.prediction.risk_level === "HIGH"
                        ? "High"
                        : prediction.prediction.risk_level === "MODERATE"
                          ? "Moderate"
                          : "Low",
                    )}
                  >
                    {prediction.prediction.risk_level}
                  </span>
                ) : (
                  <span className="badge-slate">Pending</span>
                )}
              </div>
            </div>
            {ml.error ? (
              <p className="muted text-xs">{ml.error}</p>
            ) : !prediction ? (
              <LoadingInline />
            ) : (
              <>
                <div className="flex items-baseline gap-3">
                  <span className="tabular-nums text-3xl font-semibold tracking-tight">
                    {fmtScore(prediction.prediction.risk_score)}
                  </span>
                  <span className="muted text-xs uppercase tracking-wide">
                    AI risk score · {prediction.model_name} {prediction.model_version} ·{" "}
                    {prediction.inference_mode} inference
                  </span>
                </div>
                {prediction.generated_at && (
                  <p className="muted mt-1 text-[11px]">
                    AI assessment updated{" "}
                    {new Date(prediction.generated_at).toLocaleTimeString()}
                  </p>
                )}
                {prediction.factors.length > 0 && (
                  <div className="mt-3">
                    <p className="muted mb-1 text-[10px] uppercase tracking-wide">
                      Input factors flagged
                    </p>
                    <div className="flex flex-wrap gap-1.5">
                      {prediction.factors.map((f) => (
                        <span key={f.label} className="badge-slate">
                          {f.label}: {f.value}
                        </span>
                      ))}
                    </div>
                  </div>
                )}
                {prediction.contextual && (
                  <p className="muted mt-2 text-[11px] leading-relaxed">
                    Environmental context (zone AQI signal, weight{" "}
                    {Math.round(prediction.contextual.environmental_weight * 100)}%):{" "}
                    combined {fmtScore(prediction.contextual.combined_score)} ·{" "}
                    {prediction.contextual.risk_level}
                  </p>
                )}
                <p className="muted mt-2 text-[11px] leading-relaxed">
                  Generated by model inference on synthetic features. Not clinically
                  validated.
                </p>
              </>
            )}
          </div>

          <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
            <VitalTile
              label="Blood pressure"
              value={`${patient.blood_pressure_systolic}/${patient.blood_pressure_diastolic}`}
            />
            <VitalTile label="Cholesterol" value={`${patient.cholesterol}`} />
            <VitalTile label="Glucose" value={`${patient.glucose}`} />
            <VitalTile label="BMI" value={patient.bmi.toFixed(1)} />
            <VitalTile label="Heart rate" value={`${patient.heart_rate}`} />
            <VitalTile label="Age" value={`${patient.age}`} />
          </div>

          <div className="flex flex-wrap gap-2">
            {patient.previous_cardiac_history && (
              <span className="badge-red">Cardiac history</span>
            )}
            {patient.diabetes && <span className="badge-amber">Diabetes</span>}
            {patient.hypertension && <span className="badge-sky">Hypertension</span>}
            {!patient.previous_cardiac_history &&
              !patient.diabetes &&
              !patient.hypertension && (
                <span className="badge-slate">No recorded conditions</span>
              )}
          </div>

          <div className="rounded-xl border border-line p-4">
            <div className="mb-3 flex items-center justify-between">
              <p className="panel-title">Latest risk assessment</p>
              {assessment ? (
                <span className={riskBadgeClass(assessment.risk_category)}>
                  {assessment.risk_category}
                </span>
              ) : (
                <span className="badge-slate">Not assessed</span>
              )}
            </div>
            {assessment ? (
              <div className="space-y-3">
                {[
                  {
                    label: "Cardiac risk score",
                    value: assessment.cardiac_risk_score,
                    barClass: "bg-indigo-500",
                  },
                  {
                    label: "Overall health risk score",
                    value: assessment.overall_health_risk_score,
                    barClass: "bg-red-500",
                  },
                ].map((row) => (
                  <div key={row.label}>
                    <div className="mb-1 flex items-center justify-between text-xs">
                      <span>{row.label}</span>
                      <span className="tabular-nums">{fmtScore(row.value)}</span>
                    </div>
                    <div className="h-1.5 overflow-hidden rounded-full bg-line-soft">
                      <div
                        className={`h-full rounded-full ${row.barClass}`}
                        style={{
                          width: `${Math.round(
                            Math.min(1, Math.max(0, row.value)) * 100,
                          )}%`,
                        }}
                      />
                    </div>
                  </div>
                ))}
                <p className="muted text-xs">
                  Assessed on {fmtDate(assessment.assessment_date)} for grid{" "}
                  {assessment.grid_id}
                </p>
              </div>
            ) : (
              <p className="muted text-sm">
                No risk assessment has been recorded for this patient.
              </p>
            )}
          </div>

          <p className="muted text-[11px] leading-relaxed">
            Scores shown are stored assessment records from the database. The frontend
            does not compute or predict medical risk.
          </p>
        </div>
      )}
    </Modal>
  );
}


function LoadingInline() {
  return <p className="muted animate-pulse text-xs">Running model inference…</p>;
}